export default function Head() {

  return (
    <>
      <title>Neural Talk</title>
      <script src="https://accounts.google.com/gsi/client" async defer></script>

      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <meta name="theme-color" content="#696969" />
      <link rel="icon" href="/images/favicon.ico" />
    </>
  );
}
